# 5.9. Thurs 'Boston Housing'   2017130772 정준영

### 집 값 예측 프로그램 만들기

step 1. 입.출력 결정 : 출력은 집 값=1개, 입력은 집값에 영향을 미치는 요소들 결정 ex) 지하철역으로부터의 거리(o), 집의 색깔(x), 해당 지역 세금(o), 그 지역의 정치적 경향(?) 등

step 2. 가능한 입력의 갯수를 줄이는 것이 좋음(입력이 많으면 data수집이 힘듦), 좋은 예측을 만들어낼 최소의 입력갯수 정하기(솎아내기)  ex) 해당 지역 교통량
- 입력과 출력의 데이터 모아서 plot해서 명백한 관계성(correlation)이 보이면(positive or negative) 그 입력은 솎아내지 않고 포함, 특별히 관계성이 보이지 않으면 입력에서 제외함.

https://www.kaggle.com/c/boston-housing  : 13개 변수(입력), 1개의 출력(=medv:집 값)

보스톤을 대상으로 만든 프로그램을 다른 지역에 사용해 그 지역의 집값 예측가능

* input elements
 - crim : per capita crime rate by town.  :  도시별 1인당 범죄율
 - zn : proportion of residential land zoned for lots over 25,000 sq.ft. : 25000제곱피트 이상지역에 대해  주거지 비율
 - indus : proportion of non-retail business acres per town. : 마을 당 비소매(도매) 사업 에이커(면적) 비율
 - chas : Charles River dummy variable(categorical 요소를 숫자로 표현하는데 사용하는 것) (= 1 if tract bounds river; 0 otherwise). : 찰스 강 인접여부 
 - nox : nitrogen oxides concentration (parts per 10 million). : 질소 산화물 농도
 - rm : average number of rooms per dwelling. : 주택 당 평균 방 수
 - age : proportion of owner-occupied units built prior to 1940. : 1940년 이전에 건설된 소유주 거주 주택 비율
 - dis : weighted mean of distances to five Boston employment centres. : 5개의 보스턴 고용센터까지 거리의 가중평균(접근성)
 - rad : index of accessibility to radial highways. : 방사형 고속도로 접근성 지수
 - tax : full-value property-tax rate per $10,000. : 1만달러 당 완전가치 재산세 비율
 - ptratio : pupil-teacher ratio by town. : 마을 별 학생-교사 비율 
 - black : 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town. : 마을 별 흑인 비율 
 - lstat : lower status of the population (percent). : 하위 계층의 비율
 
 
* output 
 - medv : median value of owner-occupied homes in \$1000s. : 1000달러 대 소유자 거주 주택의 미디언 값 

In [1]:
# Tensorflow and tf.keras
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

In [2]:
(x_train, y_train), (x_test, y_test) = tensorflow.keras.datasets.boston_housing.load_data(path='boston_housing.npz') 

In [4]:
model = Sequential()
model.add(Dense(1, input_shape=[13]))    # 입력 13개, 출력 1개(집 값)
model.compile(optimizer='rmsprop', loss='mse')
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 14        
Total params: 14
Trainable params: 14
Non-trainable params: 0
_________________________________________________________________


In [5]:
model.fit(x_train, y_train, epochs=1000)   # whole dataset을 1000바퀴 돌려서 학습,훈련해라

Instructions for updating:
Use tf.cast instead.
Epoch 1/1000
404/404 [==============================] - 1s 2ms/sample - loss: 47787.9276
Epoch 2/1000
404/404 [==============================] - 0s 86us/sample - loss: 41654.3776
Epoch 3/1000
404/404 [==============================] - 0s 106us/sample - loss: 36934.9762
Epoch 4/1000
404/404 [==============================] - 0s 75us/sample - loss: 32661.1874
Epoch 5/1000
404/404 [==============================] - 0s 137us/sample - loss: 28678.9104
Epoch 6/1000
404/404 [==============================] - 0s 176us/sample - loss: 24966.5506
Epoch 7/1000
404/404 [==============================] - 0s 65us/sample - loss: 21547.8216
Epoch 8/1000
404/404 [==============================] - 0s 92us/sample - loss: 18381.8562
Epoch 9/1000
404/404 [==============================] - 0s 65us/sample - loss: 15474.1112
Epoch 10/1000
404/404 [==============================] - 0s 111us/sample - loss: 12837.0548
Epoch 11/1000
404/404 [=========================

404/404 [==============================] - 0s 30us/sample - loss: 66.3311
Epoch 90/1000
404/404 [==============================] - 0s 42us/sample - loss: 64.6423
Epoch 91/1000
404/404 [==============================] - 0s 83us/sample - loss: 64.7173
Epoch 92/1000
404/404 [==============================] - 0s 35us/sample - loss: 63.5794
Epoch 93/1000
404/404 [==============================] - 0s 86us/sample - loss: 63.5559
Epoch 94/1000
404/404 [==============================] - 0s 57us/sample - loss: 62.2670
Epoch 95/1000
404/404 [==============================] - 0s 67us/sample - loss: 62.6215
Epoch 96/1000
404/404 [==============================] - 0s 58us/sample - loss: 60.8386
Epoch 97/1000
404/404 [==============================] - 0s 68us/sample - loss: 61.7112
Epoch 98/1000
404/404 [==============================] - 0s 67us/sample - loss: 60.3447
Epoch 99/1000
404/404 [==============================] - 0s 46us/sample - loss: 60.0065
Epoch 100/1000
404/404 [======================

404/404 [==============================] - 0s 42us/sample - loss: 44.7659
Epoch 182/1000
404/404 [==============================] - 0s 40us/sample - loss: 44.4727
Epoch 183/1000
404/404 [==============================] - 0s 54us/sample - loss: 44.3381
Epoch 184/1000
404/404 [==============================] - 0s 67us/sample - loss: 44.9101
Epoch 185/1000
404/404 [==============================] - 0s 66us/sample - loss: 45.4504
Epoch 186/1000
404/404 [==============================] - 0s 72us/sample - loss: 44.5482
Epoch 187/1000
404/404 [==============================] - 0s 61us/sample - loss: 44.5630
Epoch 188/1000
404/404 [==============================] - 0s 55us/sample - loss: 44.3116
Epoch 189/1000
404/404 [==============================] - 0s 72us/sample - loss: 44.5467
Epoch 190/1000
404/404 [==============================] - 0s 45us/sample - loss: 44.3143
Epoch 191/1000
404/404 [==============================] - 0s 43us/sample - loss: 45.3985
Epoch 192/1000
404/404 [============

404/404 [==============================] - 0s 82us/sample - loss: 40.2844
Epoch 274/1000
404/404 [==============================] - 0s 53us/sample - loss: 40.9691
Epoch 275/1000
404/404 [==============================] - 0s 73us/sample - loss: 40.0650
Epoch 276/1000
404/404 [==============================] - 0s 40us/sample - loss: 40.3212
Epoch 277/1000
404/404 [==============================] - 0s 84us/sample - loss: 39.7364
Epoch 278/1000
404/404 [==============================] - 0s 230us/sample - loss: 39.9256
Epoch 279/1000
404/404 [==============================] - 0s 81us/sample - loss: 40.4989
Epoch 280/1000
404/404 [==============================] - 0s 103us/sample - loss: 39.8935
Epoch 281/1000
404/404 [==============================] - 0s 24us/sample - loss: 40.0358
Epoch 282/1000
404/404 [==============================] - 0s 106us/sample - loss: 39.2567
Epoch 283/1000
404/404 [==============================] - 0s 60us/sample - loss: 39.7426
Epoch 284/1000
404/404 [=========

404/404 [==============================] - 0s 71us/sample - loss: 36.7969
Epoch 365/1000
404/404 [==============================] - 0s 75us/sample - loss: 37.0882
Epoch 366/1000
404/404 [==============================] - 0s 44us/sample - loss: 36.7480
Epoch 367/1000
404/404 [==============================] - 0s 74us/sample - loss: 36.5239
Epoch 368/1000
404/404 [==============================] - 0s 45us/sample - loss: 36.5826
Epoch 369/1000
404/404 [==============================] - 0s 83us/sample - loss: 36.9427
Epoch 370/1000
404/404 [==============================] - 0s 83us/sample - loss: 37.5934
Epoch 371/1000
404/404 [==============================] - 0s 66us/sample - loss: 36.0994
Epoch 372/1000
404/404 [==============================] - 0s 65us/sample - loss: 36.5138
Epoch 373/1000
404/404 [==============================] - 0s 36us/sample - loss: 36.1522
Epoch 374/1000
404/404 [==============================] - 0s 70us/sample - loss: 37.3255
Epoch 375/1000
404/404 [============

404/404 [==============================] - 0s 96us/sample - loss: 34.3773
Epoch 457/1000
404/404 [==============================] - 0s 81us/sample - loss: 35.0882
Epoch 458/1000
404/404 [==============================] - 0s 75us/sample - loss: 34.7669
Epoch 459/1000
404/404 [==============================] - 0s 119us/sample - loss: 34.4867
Epoch 460/1000
404/404 [==============================] - 0s 74us/sample - loss: 34.7528
Epoch 461/1000
404/404 [==============================] - 0s 59us/sample - loss: 34.8730
Epoch 462/1000
404/404 [==============================] - 0s 80us/sample - loss: 34.3003
Epoch 463/1000
404/404 [==============================] - 0s 73us/sample - loss: 34.1760
Epoch 464/1000
404/404 [==============================] - 0s 88us/sample - loss: 34.5022
Epoch 465/1000
404/404 [==============================] - 0s 26us/sample - loss: 34.3246
Epoch 466/1000
404/404 [==============================] - 0s 87us/sample - loss: 34.3594
Epoch 467/1000
404/404 [===========

404/404 [==============================] - 0s 87us/sample - loss: 32.5844
Epoch 548/1000
404/404 [==============================] - 0s 34us/sample - loss: 32.5562
Epoch 549/1000
404/404 [==============================] - 0s 83us/sample - loss: 32.9691
Epoch 550/1000
404/404 [==============================] - 0s 45us/sample - loss: 32.5361
Epoch 551/1000
404/404 [==============================] - 0s 57us/sample - loss: 32.6127
Epoch 552/1000
404/404 [==============================] - 0s 74us/sample - loss: 32.7686
Epoch 553/1000
404/404 [==============================] - 0s 227us/sample - loss: 32.6388
Epoch 554/1000
404/404 [==============================] - 0s 193us/sample - loss: 32.5546
Epoch 555/1000
404/404 [==============================] - 0s 105us/sample - loss: 32.6202
Epoch 556/1000
404/404 [==============================] - 0s 168us/sample - loss: 32.5375
Epoch 557/1000
404/404 [==============================] - 0s 126us/sample - loss: 32.7921
Epoch 558/1000
404/404 [=======

404/404 [==============================] - 0s 57us/sample - loss: 31.7378
Epoch 639/1000
404/404 [==============================] - 0s 62us/sample - loss: 31.1031
Epoch 640/1000
404/404 [==============================] - 0s 40us/sample - loss: 31.4786
Epoch 641/1000
404/404 [==============================] - 0s 38us/sample - loss: 31.2066
Epoch 642/1000
404/404 [==============================] - 0s 79us/sample - loss: 30.8209
Epoch 643/1000
404/404 [==============================] - 0s 47us/sample - loss: 31.4249
Epoch 644/1000
404/404 [==============================] - 0s 76us/sample - loss: 31.2835
Epoch 645/1000
404/404 [==============================] - 0s 71us/sample - loss: 31.2311
Epoch 646/1000
404/404 [==============================] - 0s 64us/sample - loss: 31.1529
Epoch 647/1000
404/404 [==============================] - 0s 69us/sample - loss: 30.7818
Epoch 648/1000
404/404 [==============================] - 0s 80us/sample - loss: 31.3589
Epoch 649/1000
404/404 [============

404/404 [==============================] - 0s 42us/sample - loss: 30.3630
Epoch 730/1000
404/404 [==============================] - 0s 84us/sample - loss: 29.9025
Epoch 731/1000
404/404 [==============================] - 0s 41us/sample - loss: 29.7783
Epoch 732/1000
404/404 [==============================] - 0s 81us/sample - loss: 30.2621
Epoch 733/1000
404/404 [==============================] - 0s 67us/sample - loss: 30.4457
Epoch 734/1000
404/404 [==============================] - 0s 59us/sample - loss: 29.6796
Epoch 735/1000
404/404 [==============================] - 0s 61us/sample - loss: 30.0867
Epoch 736/1000
404/404 [==============================] - 0s 67us/sample - loss: 29.9307
Epoch 737/1000
404/404 [==============================] - ETA: 0s - loss: 25.97 - 0s 48us/sample - loss: 30.0179
Epoch 738/1000
404/404 [==============================] - 0s 57us/sample - loss: 29.9793
Epoch 739/1000
404/404 [==============================] - 0s 72us/sample - loss: 30.6206
Epoch 740/10

404/404 [==============================] - 0s 77us/sample - loss: 29.3501
Epoch 821/1000
404/404 [==============================] - 0s 85us/sample - loss: 29.4710
Epoch 822/1000
404/404 [==============================] - 0s 27us/sample - loss: 29.3361
Epoch 823/1000
404/404 [==============================] - 0s 72us/sample - loss: 29.1699
Epoch 824/1000
404/404 [==============================] - 0s 48us/sample - loss: 29.3786
Epoch 825/1000
404/404 [==============================] - 0s 62us/sample - loss: 29.5589
Epoch 826/1000
404/404 [==============================] - 0s 90us/sample - loss: 28.7042
Epoch 827/1000
404/404 [==============================] - 0s 76us/sample - loss: 28.9377
Epoch 828/1000
404/404 [==============================] - 0s 38us/sample - loss: 29.5689
Epoch 829/1000
404/404 [==============================] - 0s 75us/sample - loss: 28.8936
Epoch 830/1000
404/404 [==============================] - 0s 43us/sample - loss: 29.1372
Epoch 831/1000
404/404 [============

404/404 [==============================] - 0s 57us/sample - loss: 28.6872
Epoch 913/1000
404/404 [==============================] - 0s 40us/sample - loss: 28.5096
Epoch 914/1000
404/404 [==============================] - 0s 58us/sample - loss: 29.1798
Epoch 915/1000
404/404 [==============================] - 0s 56us/sample - loss: 27.9474
Epoch 916/1000
404/404 [==============================] - 0s 76us/sample - loss: 28.7842
Epoch 917/1000
404/404 [==============================] - 0s 47us/sample - loss: 28.4501
Epoch 918/1000
404/404 [==============================] - 0s 59us/sample - loss: 27.9300
Epoch 919/1000
404/404 [==============================] - 0s 81us/sample - loss: 28.8658
Epoch 920/1000
404/404 [==============================] - 0s 53us/sample - loss: 28.8840
Epoch 921/1000
404/404 [==============================] - 0s 28us/sample - loss: 28.3685
Epoch 922/1000
404/404 [==============================] - 0s 57us/sample - loss: 28.5150
Epoch 923/1000
404/404 [============

훈련할 때 사용하지 않은 데이터(전체 데이터에서 약 20% 떼어놨다가)로 테스트 해본다.

In [6]:
model.evaluate(x_test, y_test)

102/102 [==============================] - 0s 2ms/sample - loss: 29.7589


29.758894527659695

In [7]:
print(model.input_shape)   # input에 얼마나 들어가는지 알려줌
print(model.output_shape)

(None, 13)
(None, 1)


predict: 실제로 예측이 가능한지 해 봄

In [8]:
model.predict(np.array([0,1,50,1,0,5,.5,10,1000,100,10,100,1]).reshape(1,13))

array([[198.42683]], dtype=float32)

# Practice

In [10]:
## lowering 
model.predict(np.array([5,1,40,1,0,4,.3,15,800,120,15,120,2]).reshape(1,13))

array([[154.75568]], dtype=float32)

In [11]:
##### higher
model.predict(np.array([0,1,60,1,0,7,.2,17,1200,80,5,0,0]).reshape(1,13))

array([[234.7425]], dtype=float32)