## 3.7(Thurs) variables(변수할당)

#### -변수할당 : Use '='

#### -'print': 실행의 결과값 나타내기

#### -'type': 변수의 type 정보
####  int: 정수 / float: 소수점 있는 수 / str: 문자 / 
####  list: comma(,)로 나뉘어진 요소들의 나열, [ ] 사용 / dict: list와 비슷하나, 데이터가 paired되어 있음(like dictionary)

In [1]:
a = 1; print(type(a))

<class 'int'>


In [2]:
a = 1; a = float(a); print(type(a))

<class 'float'>


In [4]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


In [7]:
print(a)

1


#### a[...]: 변수 a의 ...에 access
####  ex)a[0] = a의 가장 첫번째 요소 / a[-1] = a의 가장 마지막 요소

 * in Python, 수는 0부터 시작

In [9]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


  * list(...) : 변수 ...에 있는 요소로 list를 생성

In [11]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


 * 숫자와 문자를 함께 사용해 list를 만들 수 있음

In [13]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


 * list 안에 또 다른 list가 포함되어 있다면, access하기 위해 2번 indicate 가능

In [14]:
print(a[2][1])

4


In [16]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


* to access: 숫자가 아닌 paired된 정보를 입력하여 access

In [24]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


--------------------------------------------------------------------------------------------

## 3.14 (Thurs) numpy(행렬과 관련된 기능)

In [1]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

#### - import : 하드디스크에 저장된 것을 메모리에 올려 사용가능하게끔 불러옴 / 효율성을 위해 'as np' 통해 이름 변경
#### - numpy 내부 기능을 사용할 때는 'np.'을 붙일 것
#### - array: 행렬의 형태로 변화시키나, 그 성질은 행렬이 아님

In [2]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


* 형태는 행렬의 형태를 가지나, 그 성질은 행렬이 아니기 때문에 dimension이 맞지 않아도 곱셈이 가능(element by element로 곱해짐)

In [29]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


#### - matrix: 행렬로 변화(성질까지)

* matrix는 numpy 내부의 기능이므로 'np.'을 붙일 것 

In [30]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


* 완전한 행렬이므로 dimension이 맞지 않으면 곱셈이 불가능 

In [31]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

#### - .T: 행렬의 transpose
 * transpose통해 dimension을 맞추어 곱셈

In [32]:
c*c.T

matrix([[14, 19],
        [19, 73]])

---------------------------------------------------------------------------------------

## practice

In [6]:
a = ['korea', 'university','english','major']; print(a)

['korea', 'university', 'english', 'major']


In [7]:
a = ['korea', 'university',['english', 'language','literature']]; print(a); print(type(a))

['korea', 'university', ['english', 'language', 'literature']]
<class 'list'>


In [8]:
print(a[0]); print(a[2]); print(a[2][0]); print(a[2][-1])

korea
['english', 'language', 'literature']
english
literature


In [9]:
b = 3.141592; print(type(b))

<class 'float'>


In [13]:
print(int(b)); print(b); print(type(b))

3
3.141592
<class 'float'>


In [1]:
a = [(1,3,5),(2,4,6)]
a

[(1, 3, 5), (2, 4, 6)]

In [4]:
import numpy as np
b = np.matrix(a)
print(b)
print(type(b))

[[1 3 5]
 [2 4 6]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [5]:
print(b*b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [6]:
print(b*b.T)

[[35 44]
 [44 56]]
