## 3.7(Thurs) variables(변수할당)

#### -Allocating element to the variable : Use '='

#### -'print': show the result

#### -'type': figure out the type(class) of the variable
####  int: integer / flaot: number which has decimal place / str: text / 
####  list: a series of elements divided by comma(,) / dict: similar to list, but the data is paried

In [1]:
a = 1; print(type(a))

<class 'int'>


In [5]:
a = 1; a = float(a); print(type(a))

<class 'float'>


In [6]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


In [7]:
print(a)

1


#### a[...]: index certain element in list a   
####  ex)a[0] = the first element in list a / a[-1] = the very last element in list a

 * in Python, number begins with 0

In [9]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


  * list(...) : make a list with the elements in ...

In [11]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


 * can make list using both number and text

In [13]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


 * if a list is in another list, can indicate twice 

In [14]:
print(a[2][1])

4


In [16]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


In [24]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


In [24]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

---------------------------------------------------------------------------------------

## practice

In [17]:
a = ['korea', 'university','english','major']; print(a)

['korea', 'university', 'english', 'major']


In [19]:
a = ['korea', 'university',['english', 'language','literature']]; print(a); print(type(a))

['korea', 'university', ['english', 'language', 'literature']]
<class 'list'>


In [23]:
print(a[0]); print(a[2]); print(a[2][0]); print(a[-1])

korea
['english', 'language', 'literature']
english
['english', 'language', 'literature']


In [21]:
b = 3.141592; print(type(b))

<class 'float'>


In [25]:
print(int(b)); print(b)

3
3.141592


--------------------------------------------------------------------------------------------

In [28]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


In [29]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


In [30]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [31]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [32]:
c*c.T

matrix([[14, 19],
        [19, 73]])